[toolchain]
arcium_version = "0.9.7"

[programs.localnet]
arcium_obscura_markets = "4Bong499epakUpBjRxnfjouWnmXg718yu2KpJeRQv9yZ"

[programs.devnet]
arcium_obscura_markets = "4Bong499epakUpBjRxnfjouWnmXg718yu2KpJeRQv9yZ"

[programs.testnet]
arcium_obscura_markets = "4Bong499epakUpBjRxnfjouWnmXg718yu2KpJeRQv9yZ"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[clusters]

[clusters.devnet]
offset = 456
